DROP DATABASE IF EXISTS volunteer_db;
CREATE DATABASE volunteer_db;
USE volunteer_db;   

CREATE TABLE farmersMarket (
FMID INTEGER NOT NULL,
Name VARCHAR(250) NOT NULL,
Website VARCHAR(500) NOT NULL,
Street VARCHAR(500) NOT NULL,
City VARCHAR(50) NOT NULL,
County VARCHAR(50) NOT NULL,
State VARCHAR(50) NOT NULL,
Zipcode INTEGER NOT NULL,
PRIMARY KEY (FMID)
);

SELECT * FROM farmersMarket;